# This is a deploy template that will setup and configure routes to run the full PIMS solution.
# Components in template
#   - Route 1: API
#   - Route 2: API Swagger docs
#   - Route 3: APP
kind: Template
apiVersion: v1
metadata:
  name: pims-api-deploy
  annotations:
    openshift.io/display-name: .NET Core 3.1 Deployment Template
    description: Deployment template for a .NET Core 3.1 application.
    tags: pims-api,netcore,api
objects:
  - kind: Route
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${COMP_NAME}-${ENV_NAME}${Id}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      labels:
        name: ${APP_NAME}-${COMP_NAME}-${ENV_NAME}${Id}
        app: ${APP_NAME}
        component: ${COMP_NAME}
        env: ${ENV_NAME}
        role: backend
        id: ${APP_NAME}-${COMP_NAME}-${ENV_NAME}${ID}
    spec:
      host: ${APP_DOMAIN}
      path: ${API_PATH}
      to:
        kind: Service
        name: ${APP_NAME}-${COMP_NAME}-${ENV_NAME}${Id}
        weight: 100
      port:
        targetPort: ${APP_PORT}-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
  - kind: Route
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${COMP_NAME}-${ENV_NAME}${Id}-docs
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      labels:
        name: ${APP_NAME}-${COMP_NAME}-${ENV_NAME}${Id}-docs
        app: ${APP_NAME}
        component: ${COMP_NAME}
        env: ${ENV_NAME}
        role: backend
        id: ${APP_NAME}-${COMP_NAME}-${ENV_NAME}${ID}
    spec:
      host: ${APP_DOMAIN}
      path: ${API_DOCS_PATH}
      to:
        kind: Service
        name: ${APP_NAME}-${COMP_NAME}-${ENV_NAME}${Id}
        weight: 100
      port:
        targetPort: ${APP_PORT}-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
parameters:
  - name: APP_NAME
    displayName: App Name
    description: The name of the application (grouped).
    required: true
    value: pims
  - name: COMP_NAME
    displayName: Component Name
    description: The name of the application component (e.g ui, backend, database).
    required: true
    value: api
  - name: ENV_NAME
    displayName: Environment name
    description: The name for this environment [dev, test, prod]
    required: true
    value: dev
  - name: ID
    displayName: Unique Identifier
    description: A unique identifier to allow for multiple instances (i.e. "-01").
    value: ""
  - name: PROJECT_NAMESPACE
    displayName: OpenShift Project Namespace
    description: The namespace of the OpenShift project containing the application.
    required: true
    value: jcxjin

  - name: APP_DOMAIN
    displayName: Application Hostname
    description:
      The exposed hostname that will route to the the .NET Core service, if left blank a
      value will be defaulted.
    value: pims-dev.pathfinder.gov.bc.ca
  - name: APP_PORT
    displayName: Application Container Port
    description: The port used to communicate with the Pod
    value: "8080"
  - name: API_PATH
    displayName: API URL path
    description: The URL path to the api
    value: "/api"
  - name: API_DOCS_PATH
    displayName: API Swagger URL path
    description: The URL path to the api swagger docs
    value: "/api-docs"
