apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: oc-build
  annotations:
    tekton.dev/displayName: openshift client
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: cli
  labels:
    app.kubernetes.io/version: "0.1"
    operator.tekton.dev/provider-type: redhat
spec:
  description: >-
    This task uses the specified BuildConfig to build an image.
  params:
    - name: SOLUTION_NAME
      description: The solution name to label all objects with.
      type: string
      default: pims
    - name: APP_NAME
      description: The name of the application.
      type: string

    - name: GIT_SOURCE
      description: Identify the git source.
      type: string
      default: dev

    - name: IMAGE_TAG
      description: The tag given to the built image.
      type: string
      default: latest
  steps:
    - name: build
      image: "image-registry.openshift-image-registry.svc:5000/openshift/cli:latest"
      resources: {}
      script: |
        if [ "$(params.APP_NAME)" = "app" ]; then
          echo "Building app base image"
          oc start-build $(params.SOLUTION_NAME)-$(params.APP_NAME)-base.$(params.GIT_SOURCE) --follow --wait
        fi

        echo "Building image"
        oc start-build $(params.SOLUTION_NAME)-$(params.APP_NAME).$(params.GIT_SOURCE) --follow --wait

        if [ "$(params.IMAGE_TAG)" != "latest" ]; then
          echo "Tagging latest image"
          oc tag $(params.SOLUTION_NAME)-$(params.APP_NAME):latest $(params.SOLUTION_NAME)-$(params.APP_NAME):$(params.IMAGE_TAG)
        fi
