name: PIMS APP Cypress Tests - Dev

on:
  push:
    branches: [dev]
    paths: ['frontend/**']

jobs:
  PIMS-App-Cypress-Tests-Dev:
    runs-on: ubuntu-22.04
    # Cypress Docker image with Chrome v106 and Firefox v106 pre-installed.
    container: cypress/browsers:node18.12.0-chrome106-ff106

    steps:
      # Checkout PIMS Github Repository.
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Run Cypress E2E Tests.
      - name: Cypress Run E2E Tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          project: ./frontend
          build: npm run build
          start: npm run start
          command: npm run cypress:e2e
          config: baseUrl=https://pims-dev.apps.silver.devops.gov.bc.ca
        env:
          auth_client_id: pims-frontend-4391
          keycloak_user: ${{ secrets.CYPRESS_KEYCLOAK_USER }}
          keycloak_password: ${{ secrets.CYPRESS_KEYCLOAK_PASSWORD }}
